on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  # publish:
  #   runs-on: ubuntu-latest
  #   # needs: all
  #   #  && needs.all.result =='success'
  #   # if: github.event_name == 'workflow_dispatch' && inputs.job_to_run == 'publish'

  #   steps:
  #     # Checkout the repository
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     # Install dependencies
  #     - name: Install dependencies
  #       run: |
  #         cargo install cargo-release

  #     # create release
  #     - name: release
  #       env:
  #         CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  #       run: |
  #         echo "Releasing a version..."
  #         cargo release --execute

  #     # punlish to crates.io
  #     - name: publish
  #       env:
  #         CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  #       run: cargo publish

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    # needs: publish
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
