name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Rust toolchain
      - name: Install Rust
        run: >
          rustup update ${{ matrix.toolchain }} &&
          rustup default ${{ matrix.toolchain }} &&
          rustup component add clippy &&
          rustup component add rustfmt

      # Run Clippy (linting)
      - name: Run Clippy
        run: cargo clippy --all-targets -- -D warnings

      # Check code formatting
      - name: Check formatting
        run: cargo fmt --all --check

      # build in debug mode
      - name: Build
        run: cargo build --verbose

      # Run tests
      - name: Run tests
        run: cargo test --verbose

  release:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Rust toolchain
      - name: Install Rust
        run: >
          rustup update ${{ matrix.toolchain }} &&
          rustup default ${{ matrix.toolchain }} &&
          rustup component add clippy &&
          rustup component add rustfmt

      # build in release mode
      - name: Build
        run: cargo build --release
